// Generated by CoffeeScript 1.9.3
(function() {
  var config;

  config = {
    consumerKey: '',
    consumerSecret: '',
    developerToken: '',
    sandbox: true,
    persons: []
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config-default.js.map
