// Generated by CoffeeScript 1.9.3
(function() {
  var config;

  config = {
    env: {
      sandbox: {
        consumerKey: '',
        consumerSecret: '',
        developerToken: ''
      },
      production: {
        consumerKey: '',
        consumerSecret: '',
        developerToken: ''
      }
    },
    persons: []
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config-default.js.map
