// Generated by CoffeeScript 1.9.3
(function() {
  var Evernote, config, express, router;

  express = require('express');

  Evernote = require('evernote').Evernote;

  config = require('../config');

  router = express.Router();

  router.get('/', function(req, res, next) {
    return res.render('auth', {
      title: 'Login'
    });
  });

  router.get('/login', function(req, res, next) {
    var client, envConfig, sandbox, token;
    sandbox = req.query.sandbox ? true : false;
    token = req.query.token ? true : false;
    envConfig = sandbox ? config.env.sandbox : config.env.production;
    if (token) {
      req.session.evernote = {
        sandbox: sandbox,
        accessToken: envConfig.developerToken
      };
      return req.session.save(function() {
        return res.redirect('/');
      });
    } else {
      client = new Evernote.Client({
        consumerKey: envConfig.consumerKey,
        consumerSecret: envConfig.consumerSecret,
        sandbox: sandbox
      });
      return client.getRequestToken(req.protocol + "://" + (req.get('host')) + "/auth/callback", function(error, oauthToken, oauthTokenSecret, results) {
        if (error) {
          return res.status(500).send("Error getting OAuth request token : " + JSON.stringify(error));
        }
        req.session.evernote = {
          sandbox: sandbox,
          authTokenSecret: oauthTokenSecret
        };
        return req.session.save(function() {
          return res.redirect(client.getAuthorizeUrl(oauthToken));
        });
      });
    }
  });

  router.get('/callback', function(req, res, next) {
    var client, envConfig, oauthToken, oauthTokenSecret, oauthVerifier, ref, ref1, sandbox;
    oauthToken = req.query['oauth_token'];
    oauthVerifier = req.query['oauth_verifier'];
    oauthTokenSecret = (ref = req.session.evernote) != null ? ref.authTokenSecret : void 0;
    sandbox = (ref1 = req.session.evernote) != null ? ref1.sandbox : void 0;
    if (!oauthToken || !oauthVerifier || !oauthTokenSecret) {
      res.redirect('/auth');
      return;
    }
    envConfig = sandbox ? config.env.sandbox : config.env.production;
    client = new Evernote.Client({
      consumerKey: envConfig.consumerKey,
      consumerSecret: envConfig.consumerSecret,
      sandbox: sandbox
    });
    return client.getAccessToken(oauthToken, oauthTokenSecret, oauthVerifier, function(error, oauthAccessToken, oauthAccessTokenSecret, results) {
      req.session.evernote.accessToken = oauthAccessToken;
      return req.session.save(function() {
        return res.redirect('/');
      });
    });
  });

  router.get('/logout', function(req, res, next) {
    req.session.evernote = void 0;
    return req.session.save(function() {
      return res.redirect('/auth');
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=auth.js.map
