// Generated by CoffeeScript 1.10.0
(function() {
  var Evernote, core, express, router;

  express = require('express');

  Evernote = require('evernote').Evernote;

  core = require('../lib/core');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res, next) {
    var client, ref, sandbox, token, userStore;
    if (!((ref = req.session.evernote) != null ? ref.token : void 0)) {
      return res.redirect('/auth');
    } else {
      sandbox = req.session.evernote.sandbox;
      token = req.session.evernote.token;
      client = new Evernote.Client({
        token: token,
        sandbox: sandbox
      });
      userStore = client.getUserStore();
      return userStore.getUser(function(err, user) {
        if (err) {
          return res.redirect('/auth');
        }
        req.session.evernote.user = user;
        return req.session.save(function() {
          return core.www.initUser(user.username, token, sandbox, function() {
            return res.render('index', {
              title: 'Evernote Tasklog'
            });
          });
        });
      });
    }
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
