// Generated by CoffeeScript 1.9.3
(function() {
  var Evernote, core, express, router;

  express = require('express');

  router = express.Router();

  Evernote = require('Evernote').Evernote;

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    var noteStore;
    noteStore = core.client.getNoteStore();
    return noteStore.getNote(req.query.guid, true, false, false, false, (function(_this) {
      return function(err, note) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(note);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=notes.js.map
