// Generated by CoffeeScript 1.9.3
(function() {
  var NoteModel, core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  NoteModel = require('../lib/models/note-model');

  router.get('/', function(req, res, next) {
    var query;
    query = req.query.query ? JSON.parse(req.query.query) : {};
    if (req.query.content) {
      return NoteModel.prototype.s_findLocalWithContent(query, (function(_this) {
        return function(err, notes) {
          if (err) {
            return res.status(500).send(err);
          }
          return res.json(notes);
        };
      })(this));
    } else {
      return NoteModel.prototype.s_findLocalWithoutContent(query, (function(_this) {
        return function(err, notes) {
          if (err) {
            return res.status(500).send(err);
          }
          return res.json(notes);
        };
      })(this));
    }
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=notes.js.map
