// Generated by CoffeeScript 1.9.3
(function() {
  var Evernote, core, express, router;

  express = require('express');

  router = express.Router();

  Evernote = require('Evernote').Evernote;

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    var noteStore;
    noteStore = core.client.getNoteStore();
    return noteStore.listNotebooks((function(_this) {
      return function(err, notebooks) {
        if (err) {
          return req.status(500).send(err);
        }
        return res.json(notebooks);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=notebooks.js.map
