// Generated by CoffeeScript 1.10.0
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.notes.findLocal(req.query, (function(_this) {
      return function(err, notes) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(notes);
      };
    })(this));
  });

  router.get('/get-content', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.notes.getRemoteContent(req.query, (function(_this) {
      return function(err, result) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(result);
      };
    })(this));
  });

  router.get('/count', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.notes.countLocal(req.query, function(err, count) {
      if (err) {
        return res.status(500).send(err);
      }
      return res.json(count);
    });
  });

  router.get('/re-parse', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.notes.reParseNotes(req.query, function(err) {
      if (err) {
        return res.status(500).send(err);
      }
      return res.json(true);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=notes.js.map
