// Generated by CoffeeScript 1.9.3
(function() {
  var NotebookModel, express, router;

  express = require('express');

  router = express.Router();

  NotebookModel = require('../lib/models/notebook-model');

  router.get('/', function(req, res, next) {
    return NotebookModel.prototype.s_findLocal(req.session.evernote.user.username, req.query, (function(_this) {
      return function(err, notebooks) {
        if (err) {
          return req.status(500).send(err);
        }
        return res.json(notebooks);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=notebooks.js.map
