// Generated by CoffeeScript 1.9.3
(function() {
  var ProfitLogModel, express, routeCommon, router;

  express = require('express');

  router = express.Router();

  routeCommon = require('./route-common');

  ProfitLogModel = require('../lib/models/profit-log-model');

  router.all('/', function(req, res, next) {
    var params;
    params = routeCommon.mergeParams(req);
    return ProfitLogModel.prototype.s_findLocal(params, function(err, profitLogs) {
      if (err) {
        return res.status(500).send(err);
      }
      return res.json(profitLogs);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=profit-logs.js.map
