// Generated by CoffeeScript 1.9.3
(function() {
  var RouteCommon, merge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  merge = require('merge');

  RouteCommon = (function() {
    function RouteCommon() {
      this.mergeParams = bind(this.mergeParams, this);
    }

    RouteCommon.prototype.mergeParams = function(req) {
      var body, query, ref, ref1;
      body = (ref = req.body) != null ? ref : {};
      query = (ref1 = req.query) != null ? ref1 : {};
      return merge(true, body, query);
    };

    return RouteCommon;

  })();

  module.exports = new RouteCommon();

}).call(this);

//# sourceMappingURL=route-common.js.map
