// Generated by CoffeeScript 1.9.3
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    if (!req.query.key) {
      return res.status(500).send('Read settings need key parameter.');
    }
    return core.users[req.session.evernote.user.username].models.settings.loadLocal(req.query.key, (function(_this) {
      return function(err, setting) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(setting);
      };
    })(this));
  });

  router.put('/save', function(req, res, next) {
    if (!req.body.key) {
      return res.status(500).send('No key.');
    }
    if (!req.body.data) {
      return res.status(500).send('No data.');
    }
    return core.users[req.session.evernote.user.username].models.settings.saveLocal(req.body.key, req.body.data, (function(_this) {
      return function(err) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(true);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=settings.js.map
