// Generated by CoffeeScript 1.9.3
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.notebooks.findLocal(req.query, (function(_this) {
      return function(err, notebooks) {
        if (err) {
          return req.status(500).send(err);
        }
        return res.json(notebooks);
      };
    })(this));
  });

  router.put('/save', function(req, res, next) {
    if (!req.body.key) {
      return req.status(500).send('No key.');
    }
    if (!req.body.data) {
      return req.status(500).send('No data.');
    }
    return core.users[req.session.evernote.user.username].models.settings.saveLocal(req.body.key, req.body.data, (function(_this) {
      return function(err) {
        if (err) {
          return req.status(500).send(err);
        }
        return res.json(true);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=settings.js.map
