// Generated by CoffeeScript 1.10.0
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    var key, ref;
    key = (ref = req.query.key) != null ? ref : null;
    return core.users[req.session.evernote.user.username].models.settings.loadLocal(key, (function(_this) {
      return function(err, settings) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(settings);
      };
    })(this));
  });

  router.put('/save', function(req, res, next) {
    if (!req.body.key) {
      return res.status(500).send('No key.');
    }
    return core.users[req.session.evernote.user.username].models.settings.saveLocal(req.body.key, req.body.value, (function(_this) {
      return function(err) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(true);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=settings.js.map
