// Generated by CoffeeScript 1.10.0
(function() {
  var express, router, www;

  express = require('express');

  router = express.Router();

  www = require('../lib/www');

  router.get('/', function(req, res, next) {
    return www.sync(req.session.evernote.user.username, (function(_this) {
      return function(err) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json('OK');
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=sync.js.map
