// Generated by CoffeeScript 1.10.0
(function() {
  var core, express, routeCommon, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  routeCommon = require('./route-common');

  router.all('/', function(req, res, next) {
    var params;
    params = routeCommon.mergeParams(req);
    return core.users[req.session.evernote.user.username].models.timeLogs.findLocal(params, function(err, timeLogs) {
      if (err) {
        return res.status(500).send(err);
      }
      return res.json(timeLogs);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=time-logs.js.map
