// Generated by CoffeeScript 1.9.3
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    return core.db.timeLogs.find({}, (function(_this) {
      return function(err, timeLogs) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(timeLogs);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=time-logs.js.map
