// Generated by CoffeeScript 1.9.3
(function() {
  var TimeLogModel, express, routeCommon, router;

  express = require('express');

  router = express.Router();

  routeCommon = require('./route-common');

  TimeLogModel = require('../lib/models/time-log-model');

  router.all('/', function(req, res, next) {
    var params;
    params = routeCommon.mergeParams(req);
    return TimeLogModel.prototype.s_findLocal(params, function(err, timeLogs) {
      if (err) {
        return res.status(500).send(err);
      }
      return res.json(timeLogs);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=time-logs.js.map
