// Generated by CoffeeScript 1.9.3
(function() {
  var UserModel, express, router;

  express = require('express');

  router = express.Router();

  UserModel = require('../lib/models/user-model');

  router.get('/', function(req, res, next) {
    return UserModel.prototype.s_loadLocal((function(_this) {
      return function(err, user) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(user);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=user.js.map
