// Generated by CoffeeScript 1.10.0
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    return core.users[req.session.evernote.user.username].models.users.loadLocal((function(_this) {
      return function(err, user) {
        if (err) {
          return res.status(500).send(err);
        }
        return res.json(user);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=user.js.map
