// Generated by CoffeeScript 1.9.3
(function() {
  var core, express, router;

  express = require('express');

  router = express.Router();

  core = require('../lib/core');

  router.get('/', function(req, res, next) {
    var userStore;
    userStore = core.client.getUserStore();
    return userStore.getUser((function(_this) {
      return function(err, user) {
        if (err) {
          res.json(err);
        }
        return res.json(user);
      };
    })(this));
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=user.js.map
