// Generated by CoffeeScript 1.9.3
(function() {
  var Model;

  Model = (function() {
    function Model() {}

    return Model;

  })();

  module.exports = Model;

}).call(this);

//# sourceMappingURL=model.js.map
