// Generated by CoffeeScript 1.10.0
(function() {
  var Datastore, Model, inflection;

  Datastore = require('nedb');

  inflection = require('inflection');

  Model = (function() {

    /**
     * @const
     * @type {string}
     */
    Model.prototype.PLURAL_NAME = '';


    /**
     * @const
     * @type {string}
     */

    Model.prototype.TITLE_FIELD = 'name';


    /**
     * @const
     * @type {boolean}
     */

    Model.prototype.REQUIRE_USER = true;


    /**
     * @protected
     * @type {string}
     */

    Model.prototype._username = null;


    /**
     * @protected
     * @type {Datastore}
     */

    Model.prototype._datastore = null;


    /**
     * @constructor
     * @param {string} username
     */

    function Model(username) {
      var dbPath;
      if (username == null) {
        username = null;
      }
      if (this.REQUIRE_USER && !username) {
        throw new Error(this.constructor.name + " need username.");
      }
      dbPath = __dirname + '/../../db/' + (username ? username + '/' : '');
      this._username = username;
      this._datastore = new Datastore({
        filename: dbPath + inflection.transform(this.PLURAL_NAME, ['underscore', 'dasherize']) + '.db',
        autoload: true
      });
    }

    return Model;

  })();

  module.exports = Model;

}).call(this);

//# sourceMappingURL=model.js.map
