// Generated by CoffeeScript 1.9.3
(function() {
  var Model, MultiModel, async, core, merge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  async = require('async');

  merge = require('merge');

  core = require('../core');

  Model = require('./Model');

  MultiModel = (function(superClass) {
    extend(MultiModel, superClass);

    function MultiModel() {
      this.s_removeLocal = bind(this.s_removeLocal, this);
      this.s_saveLocal = bind(this.s_saveLocal, this);
      this.s_findLocal = bind(this.s_findLocal, this);
      return MultiModel.__super__.constructor.apply(this, arguments);
    }


    /**
     * @protected
     * @static
     * @param {Object} query
     * @param {function} callback
     */

    MultiModel.prototype.s_findLocal = function(query, callback) {
      var limit, sort;
      merge(query, {
        deleted: null
      });
      sort = {
        updated: -1
      };
      limit = 50;
      return core.db[this.PLURAL_NAME].find(query).sort(sort).limit(limit).exec(callback);
    };


    /**
     * @public
     * @static
     * @param {Array.<Object>|Object} docs
     * @param {function} callback
     */

    MultiModel.prototype.s_saveLocal = function(docs, callback) {
      if (!docs || docs.length === 0) {
        return callback();
      }
      if (!Array.isArray(docs)) {
        docs = [docs];
      }
      core.loggers.system.debug("Save local " + this.PLURAL_NAME + " start. docs.count=" + docs.length);
      return async.eachSeries(docs, (function(_this) {
        return function(doc, callback) {
          var localDoc;
          localDoc = null;
          return async.waterfall([
            function(callback) {
              return core.db[_this.PLURAL_NAME].find({
                guid: doc.guid
              }, callback);
            }, function(docs, callback) {
              localDoc = docs.length === 0 ? null : docs[0];
              if (localDoc && localDoc.updateSequenceNum >= doc.updateSequenceNum) {
                core.loggers.system.debug("Upsert " + _this.PLURAL_NAME + " skipped. guid=" + doc.guid + ", title=" + doc[_this.TITLE_FIELD]);
                return callback();
              } else {
                core.loggers.system.debug("Upsert " + _this.PLURAL_NAME + " start. guid=" + doc.guid + ", title=" + doc[_this.TITLE_FIELD]);
                return async.waterfall([
                  function(callback) {
                    return core.db[_this.PLURAL_NAME].update({
                      guid: doc.guid
                    }, doc, {
                      upsert: true
                    }, callback);
                  }, function() {
                    var callback, i, newDoc, numReplaced;
                    numReplaced = arguments[0], newDoc = 3 <= arguments.length ? slice.call(arguments, 1, i = arguments.length - 1) : (i = 1, []), callback = arguments[i++];
                    core.loggers.system.debug("Upsert " + _this.PLURAL_NAME + " end. guid=" + doc.guid + ", numReplaced=" + numReplaced);
                    return callback();
                  }
                ], callback);
              }
            }
          ], callback);
        };
      })(this), callback);
    };


    /**
     * @public
     * @static
     * @param {Array.<string>|string} guids
     * @param {function} callback
     */

    MultiModel.prototype.s_removeLocal = function(guids, callback) {
      if (!guids || guids.length === 0) {
        return callback();
      }
      if (!Array.isArray(guids)) {
        guids = [guids];
      }
      core.loggers.system.debug("Remove local " + this.PLURAL_NAME + " start. guids.count=" + guids.length);
      return core.db[this.PLURAL_NAME].remove({
        guid: {
          $in: guids
        }
      }, (function(_this) {
        return function(err, numRemoved) {
          if (err) {
            return callback(err);
          }
          core.loggers.system.debug("Remove local " + _this.PLURAL_NAME + " end. numRemoved=" + numRemoved);
          return callback();
        };
      })(this));
    };

    return MultiModel;

  })(Model);

  module.exports = MultiModel;

}).call(this);

//# sourceMappingURL=multi-model.js.map
