// Generated by CoffeeScript 1.9.3
(function() {
  var Model, NotebookModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Model = require('./model');

  NotebookModel = (function(superClass) {
    extend(NotebookModel, superClass);

    function NotebookModel() {
      return NotebookModel.__super__.constructor.apply(this, arguments);
    }


    /**
     * @override
     */

    NotebookModel.prototype.PLURAL_NAME = 'notebooks';

    return NotebookModel;

  })(Model);

  module.exports = NotebookModel;

}).call(this);

//# sourceMappingURL=notebook-model.js.map
