// Generated by CoffeeScript 1.9.3
(function() {
  var Model, SearchModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Model = require('./model');

  SearchModel = (function(superClass) {
    extend(SearchModel, superClass);

    function SearchModel() {
      return SearchModel.__super__.constructor.apply(this, arguments);
    }

    SearchModel.prototype.PLURAL_NAME = 'searches';

    SearchModel.prototype.TITLE_FIELD = 'name';

    return SearchModel;

  })(Model);

  module.exports = SearchModel;

}).call(this);

//# sourceMappingURL=search-model.js.map
