// Generated by CoffeeScript 1.10.0
(function() {
  var MultiModel, SearchModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MultiModel = require('./multi-model');

  SearchModel = (function(superClass) {
    extend(SearchModel, superClass);

    function SearchModel() {
      return SearchModel.__super__.constructor.apply(this, arguments);
    }


    /**
     * @override
     */

    SearchModel.prototype.PLURAL_NAME = 'searches';

    return SearchModel;

  })(MultiModel);

  module.exports = SearchModel;

}).call(this);

//# sourceMappingURL=search-model.js.map
