// Generated by CoffeeScript 1.9.3
(function() {
  var Model, SettingModel, core, merge,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  merge = require('merge');

  core = require('../core');

  Model = require('./Model');

  SettingModel = (function(superClass) {
    extend(SettingModel, superClass);

    function SettingModel() {
      this.saveLocal = bind(this.saveLocal, this);
      this.loadLocal = bind(this.loadLocal, this);
      return SettingModel.__super__.constructor.apply(this, arguments);
    }


    /**
     * @override
     */

    SettingModel.prototype.PLURAL_NAME = 'settings';


    /**
     * @override
     */

    SettingModel.prototype.REQUIRE_USER = false;


    /**
     * @public
     * @param {string} key
     * @param {function} callback
     */

    SettingModel.prototype.loadLocal = function(key, callback) {
      core.loggers.system.debug("Load local " + this.PLURAL_NAME + " was started.");
      return this._datastore.find({
        _id: key
      }).sort({}).limit(1).exec((function(_this) {
        return function(err, docs) {
          var doc;
          core.loggers.system.debug("Load local " + _this.PLURAL_NAME + " was " + (err ? 'failed' : 'succeed') + ". docs.length=" + docs.length);
          if (err) {
            return callback(err);
          }
          doc = docs.length === 0 ? null : docs[0];
          return callback(null, doc);
        };
      })(this));
    };


    /**
     * @public
     * @param {Object} doc
     * @param {function} callback
     */

    SettingModel.prototype.saveLocal = function(key, doc, callback) {
      doc._id = key;
      return this._datastore.update({
        _id: key
      }, doc, {
        upsert: true
      }, (function(_this) {
        return function(err, numReplaced, newDoc) {
          if (err) {
            return callback(err);
          }
          core.loggers.system.debug("Upsert " + _this.PLURAL_NAME + " end. numReplaced=" + numReplaced);
          return callback();
        };
      })(this));
    };

    return SettingModel;

  })(Model);

  module.exports = SettingModel;

}).call(this);

//# sourceMappingURL=setting-model.js.map
