// Generated by CoffeeScript 1.10.0
(function() {
  var MultiModel, TagModel,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MultiModel = require('./multi-model');

  TagModel = (function(superClass) {
    extend(TagModel, superClass);

    function TagModel() {
      return TagModel.__super__.constructor.apply(this, arguments);
    }


    /**
     * @override
     */

    TagModel.prototype.PLURAL_NAME = 'tags';

    return TagModel;

  })(MultiModel);

  module.exports = TagModel;

}).call(this);

//# sourceMappingURL=tag-model.js.map
