// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = {
    env: {
      sandbox: {
        consumerKey: '',
        consumerSecret: ''
      },
      production: {
        consumerKey: '',
        consumerSecret: ''
      }
    }
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config.js.map
