// Generated by CoffeeScript 1.9.3

/**
 * @type {Object}
 */

(function() {
  var core;

  core = {
    app: null,
    server: null,
    www: null,
    client: null,
    db: {
      notes: null
    }
  };

  module.exports = core;

}).call(this);

//# sourceMappingURL=core.js.map
