// Generated by CoffeeScript 1.9.3

/**
 * @type {Object}
 */

(function() {
  var core, user;

  core = {
    app: null,
    server: null,
    www: null,
    loggers: {
      system: null,
      access: null,
      error: null
    },
    models: {
      settings: null
    },
    users: {}
  };

  user = {
    client: null,
    user: null,
    models: {
      linkedNotebooks: null,
      notes: null,
      notebooks: null,
      profitLogs: null,
      searches: null,
      settings: null,
      syncStates: null,
      tags: null,
      timeLogs: null,
      users: null
    }
  };

  module.exports = core;

}).call(this);

//# sourceMappingURL=core.js.map
